# ARRAY

In [2]:
import array as arr

In [3]:
a = arr.array('i',[1,2,3])  #creating an array a

In [4]:
a

array('i', [1, 2, 3])

In [6]:
b = arr.array('i',[4,5,6])  # creating an array b


In [7]:
b


array('i', [4, 5, 6])

*slicing*

In [8]:
a[0:1]

array('i', [1])

In [9]:
a[1:]

array('i', [2, 3])

*length*

In [10]:
a[0:]

array('i', [1, 2, 3])

In [11]:
len(a)      

3

In [12]:
len(b)

3

*append*

In [19]:
a.append(4)

In [15]:
a

array('i', [1, 2, 3, 4])

In [17]:
b.append(0)

In [18]:
b

array('i', [4, 5, 6, 0])

In [30]:
a[::-1]            #slicing

array('i', [4, 3, 2, 1])

*removing*

In [25]:
a.pop(4)
a

array('i', [1, 2, 3, 4])

In [33]:
for i in a:
    print(i,end=" ")                  # for loop

1 2 3 4 

In [34]:
for i in b:
    print(i,end=" ")

5 6 0 4 

In [35]:
a+b    #concatenation

array('i', [1, 2, 3, 4, 5, 6, 0, 4])

# Numpy

In [36]:
import numpy as np

In [39]:
a = np.array([(1,2,3),(4,5,6)])              #creating an numpy array
b = np.array([(5,7,9),(4,6,8)])

In [40]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b

array([[5, 7, 9],
       [4, 6, 8]])

In [43]:
a.ndim      #dimension of a

2

In [44]:
b.ndim     #dimension of b

2

In [45]:
a.itemsize       #finding itemsize 

4

In [46]:
b.dtype      #finding datatype

dtype('int32')

In [47]:
a.size       #finding size

6

In [48]:
a.shape          #finding shape

(2, 3)

In [49]:
a.reshape(3,2)       #reshaping

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
a[0,2]                 #slicing

3

In [52]:
b[0::-1]

array([[5, 7, 9]])

In [58]:
a=np.linspace(1,4,10)           #finding linspace

In [59]:
a

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [64]:
b =np.linspace(8,5,2)
b                                      # finding linspace

array([8., 5.])

In [66]:
a.max()        #finding max

4.0

In [67]:
a.min()          #finding min

1.0

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [71]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [72]:
x+y                       #addition

array([5, 7, 9])

In [75]:
np.sqrt(x)                #finding square root

array([1.        , 1.41421356, 1.73205081])

In [76]:
np.std(y)                #finding standard deviation

0.816496580927726

In [79]:
x.ravel()

array([1, 2, 3])

In [85]:
k = np.array([(3,4,5),(6,7,8)])
k         

array([[3, 4, 5],
       [6, 7, 8]])

In [86]:
k.sum(axis=0)                          #sum operation

array([ 9, 11, 13])

In [87]:
k.sum(axis=1)                 #sum operation

array([12, 21])

In [88]:
k.ravel()               #ravel

array([3, 4, 5, 6, 7, 8])

In [90]:
np.hstack(k)          #horizontal 

array([3, 4, 5, 6, 7, 8])

In [91]:
np.vstack(k)            #vertical

array([[3, 4, 5],
       [6, 7, 8]])